from CybORG.Simulator.Scenarios.EnterpriseScenarioGenerator import SUBNET

SUBNET_AGENT_MAP = {
    SUBNET.RESTRICTED_ZONE_A: 0,
    SUBNET.OPERATIONAL_ZONE_A: 1,
    SUBNET.RESTRICTED_ZONE_B: 2,
    SUBNET.OPERATIONAL_ZONE_B: 3,
    SUBNET.CONTRACTOR_NETWORK: -1,
    SUBNET.PUBLIC_ACCESS_ZONE: 4,
    SUBNET.ADMIN_NETWORK: 4,
    SUBNET.OFFICE_NETWORK: 4,
    SUBNET.INTERNET: -1
}